[workspace]
authors = ["tdehoff <tatianadehoff@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoBLAS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "<1.0.0"
scipy = ">=1.17.0,<2"
numpy = ">=2.4.1,<3"
